from services.auth import auth
from services.article import article
from services.permission import permission
from services.course import course
from services.record import record
from services.role import role
from services.user import user
from services.quiz_mcq import quiz_mcq_bp
from services.ai_service import ai_service